export enum DoctorSpecialization {
  GENERAL_PHYSICIAN = 'GENERAL_PHYSICIAN',
  CARDIOLOGIST = 'CARDIOLOGIST',
  DERMATOLOGIST = 'DERMATOLOGIST',
  ORTHOPEDIC = 'ORTHOPEDIC',
  PEDIATRICIAN = 'PEDIATRICIAN',
  NEUROLOGIST = 'NEUROLOGIST',
}
